version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  pre_build:
    commands:
      - echo "Login no ECR"
      - aws --version
      - REPOSITORY_URI=${ECR_REPO}
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-build-$(date +%Y%m%d%H%M%S)}

  build:
    commands:
      - echo "Construindo imagem Docker a partir do diretório raiz"
      - |
        if [ -f Dockerfile ]; then
          docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} .
        else
          echo "❌ Dockerfile não encontrado na raiz do projeto"; exit 1
        fi

  post_build:
    commands:
      - echo "Push da imagem para o Amazon ECR"
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:latest

      # Geração dos manifests Kubernetes
      - echo "Gerando manifestos Kubernetes com a imagem ${REPOSITORY_URI}:${IMAGE_TAG}"
      - mkdir -p dist/k8s
      - |
        if [ -f k8s/deployment.yaml ]; then
          sed "s|IMAGE_URI_PLACEHOLDER|${REPOSITORY_URI}:${IMAGE_TAG}|g" k8s/deployment.yaml > dist/k8s/deployment.yaml
        else
          echo "❌ Arquivo k8s/deployment.yaml não encontrado"; exit 1
        fi
      - |
        if [ -f k8s/service.yaml ]; then
          cp k8s/service.yaml dist/k8s/service.yaml
        else
          echo "⚠️ Aviso: arquivo k8s/service.yaml não encontrado, continuando mesmo assim"
        fi

      # Metadados para o próximo estágio (deploy)
      - printf '{"repositoryUri":"%s","imageTag":"%s"}' "${REPOSITORY_URI}" "${IMAGE_TAG}" > dist/imageDetail.json
      - echo "✅ Build finalizado com sucesso"

artifacts:
  files:
    - dist/**/*
    - buildspec-deploy.yml
  discard-paths: no